# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches:
      - main
      - master
      - fix/get_user_by_email
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo usermod -aG docker $USER

    - name: Start Docker Compose Services
      run: |
        docker-compose up -d
        sleep 20

    - name: Verify MongoDB Connection
      run: |
        docker-compose exec mongodb mongo --eval "db.runCommand({ ping: 1 })"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r backend/requirements.pip

    - name: Run Unit Tests
      run: |
        docker-compose exec backend pytest -v
